---
title: "Final Project"
author: "Leroy Ozores"
output:
  slidy_presentation:
    highlight: default
  powerpoint_presentation: default
  beamer_presentation:
    highlight: default
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(tidyverse)
library(ggplot2)

#Packages Required

tuesdata <- tidytuesdayR::tt_load('2022-11-29')
tuesdata <- tidytuesdayR::tt_load(2022, week = 48)

wcmatches <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-11-29/wcmatches.csv')
worldcups <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-11-29/worldcups.csv')
```

# Introduction

The FIFA World Cup! One of the most exciting tournament in the world that occurs every four year (in my opinion). The World Cup is between national teams from all over the world. 

The data that I will be using 

```{r}
ggplot(worldcups, aes(x = year, y = attendance, fill = attendance)) +
  geom_line()
```


